### PR TITLE
Fix MifareDesfire_WriteDataAsync:

### PR DESCRIPTION
**Pull request by Xentrice**
EncryptionMode byte added to transferred data

### CODE REVIEW

**Comment by Xentrice** [comment]
Note:
Im using TWN4/B1.62/CCF4.80/PRS1.04
BIX 4.80

Please ensure this is not caused by version mismatch.

**Comment by c3rebro** [comment]
Whoops. Thank you for contributing here. As i was reviewing this, i recognised "createFile" is also missing the cryptomode byte... i will look after that right away

**Review by c3rebro — APPROVED** [review]
Gosh. No, it is not reader specific. You are right. it was just missing. Thank you for contributing.

**Comment by Xentrice** [comment]
Interesting, i was using createFile without Problem. Desfire Docs are sparse and hint at this byte only being required with encryption, yet i testet multiple times and it seems the byte is required with and without. I'm not sure, but i guess it's reader firmware stuff.

**Comment by Xentrice** [comment]
with createFile, i only used unencrypted mode tho. maybe the reader adds the byte here and doesn't on writeData, maybe Desfire can handle one and not the other. I'll run some tests and if I find someting interesting, ill let you know!
Thanks for merging, and a big thank you for your work!

**Comment by c3rebro** [comment]
> Interesting, i was using createFile without Problem. Desfire Docs are sparse and hint at this byte only being required with encryption, yet i testet multiple times and it seems the byte is required with and without. I'm not sure, but i guess it's reader firmware stuff.

No, i responded too quickly because of an old method signature in my test application. There, a encmode byte was given for no reason. i realized this later when reading the reader docs. thus, i deleted my comment.

**Pull request merged**
